spring:
  application:
    name: OfflineDataService
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/infinitechat?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  data:
    redis:
      database: 2
      host: localhost
      port: 6379
      password: ${REDIS_PASSWORD}
      timeout: 30000
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}  # Kafka 服务地址，多个用逗号分隔
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 3
    consumer:
      group-id: infinite-chat-push-group                # 消费者组 ID
      auto-offset-reset: earliest       # earliest / latest / none
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: true          # 是否自动提交 offset
      auto-commit-interval: 1000        # 自动提交间隔（毫秒）
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:localhost:18375}

canal:
  server:
    host: localhost
    port: 11111
  destination: example
  username: ${CANAL_USERNAME}
  password: ${CANAL_PASSWORD}
  filter: ".*\\..*"
  client:
    heartbeat:
      interval: 2000
      timeout: 3000
    socket:
      timeout: 6000

server:
  port: 8101
