spring:
  application:
    name: RedPacketService
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:49152/InfiniteChat?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: [REDACTED]
  data:
    redis:
      database: 2
      host: localhost
      port: 6379
      timeout: 30000

server:
  port: 8103
